#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  48000
#define AUDIO_OUTPUT_SAMPLE_RATE 48000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_16
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_18
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_17
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_47
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define LCD_SPI_HOST       SPI2_HOST
#define LCD_SPI_SCLK_PIN   GPIO_NUM_12
#define LCD_SPI_MOSI_PIN   GPIO_NUM_11
#define LCD_SPI_CS_PIN     GPIO_NUM_10
#define LCD_DC_PIN         GPIO_NUM_9
#define LCD_RST_PIN        GPIO_NUM_8
#define LCD_BACKLIGHT_PIN  GPIO_NUM_4
#define LCD_BACKLIGHT_OUTPUT_INVERT false
#define LCD_BACKLIGHT_DEFAULT_BRIGHTNESS 80
#define LCD_PIXEL_CLOCK_HZ (20 * 1000 * 1000)

#define DISPLAY_WIDTH        240
#define DISPLAY_HEIGHT       320
#define DISPLAY_OFFSET_X     0
#define DISPLAY_OFFSET_Y     0
#define DISPLAY_MIRROR_X     false
#define DISPLAY_MIRROR_Y     false
#define DISPLAY_SWAP_XY      false
#define DISPLAY_INVERT_COLOR true


// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_20

#endif // _BOARD_CONFIG_H_
